apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ pv_name }}"
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "{{ sc_name }}"
  local:
    path: "{{ pv_path }}"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "{{ node_name }}"
