apiVersion: v1
kind: Service
metadata:
  name: swap-service
  labels:
    app: swap
    tier: application
  namespace: default
spec:
  type: NodePort
  selector:
    app: swap
  ports:
    - targetPort: 8000 # port that containers are listening on
      port: 8000 # port number exposed internally in the cluster
      nodePort: 30007