apiVersion: apps/v1
kind: Deployment
metadata:
  name: swap
  labels:
    app: swap
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swap
  template:
    metadata:
      labels:
        app: swap
    spec:
      containers:
      - name: swap
        image: "{{ swap_image }}"
        env:
        - name: DB_HOST
          value: "{{ db_host }}"
        - name: DB_DATABASE
          value: "{{ db_name }}"
        - name: DB_USERNAME
          value: "{{ db_username }}"
        - name: DB_PASSWORD
          value: "{{ db_password }}"
        ports:
        - containerPort: 8000